### ISSUE TITLE
invalid ts generated from valid abi

### ISSUE THREAD

**Issue by jdheeter** [greymass/abi2core#1]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/2530957/160186657-52dd2584-410d-4d50-b1e9-05e8c9a18022.png">

types and abi
https://gist.github.com/jdheeter/e6097a1c785b5fd80a7125a82d484dd1

the abi seems to be working properly, on testnet.
https://wax-test.bloks.io/account/waxcontract1?loadContract=true&tab=Tables&account=waxcontract1&scope=waxcontract1&limit=100&table=editions

**Comment by jnordberg** [comment]
What generated this ABI? It's technically valid but this strange type alias is what's breaking things:

```
  "types": [
    {
      "new_type_name": "vector<uint32>",
      "type": "uint32[]"
    }
  ],
```

**Comment by jnordberg** [comment]
Another issue with your ABI is that it re-declares the builtin extended_asset, I'm not sure what the behaviour should be there since there is no formal specification for the format but I'm pretty sure you'd run into issues if your re-declared builtin ever diverged from the actual builtin type where different encoders would interpret the ABI differently

**Comment by jnordberg** [comment]
I've published version 1.1.0 of the package on npm with some fixes. I've verified that the typescript file generated by your ABI is free of type errors but not that it will actually work when encoding. Let me know if it works as expected

**Comment by jdheeter** [comment]
> What generated this ABI? It's technically valid but this strange type alias is what's breaking things:
> 
> ```
>   "types": [
>     {
>       "new_type_name": "vector<uint32>",
>       "type": "uint32[]"
>     }
>   ],
> ```

The ABI is generated by clsdk, it's still in alpha so likely there is some issues that Todd should know about. Will try with your updated library and see if there is an improvement.

**Comment by jdheeter** [comment]
latest update resolves the issue with this abi 👍
